version: "3.8"

services:
  backend:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=testcrt
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - postgres
    networks:
      backend:


  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=testcrt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:


volumes:
  postgres_data:

networks:
  backend: