version: "3.8"

services:
  unlimsoft_test_task:
    image: umbreella/unlimsoft_test_task:latest
    container_name: unlimsoft_test_task
    restart: always
    ports:
      - 8000:8000
    environment:
      - APP_POSTGRES_USERNAME=postgres
      - APP_POSTGRES_PASSWORD=password
      - APP_POSTGRES_DB=testcrt
      - APP_POSTGRES_HOST=postgres13
    depends_on:
      - postgres
    networks:
      backend:

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testcrt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:


volumes:
  postgres_data:

networks:
  backend: