name: FastAPI CI - Tests and Push on DockerHub

on:
  push:
    branches: [ main ]

jobs:
  tests_and_deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6

      - name: Install Dependencies For Python
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --without dev

      - name: Update pytest.ini
        run: |
          echo "${{ secrets.PYTEST_INI }}" > pytest.ini

      - name: Generate coverage report
        env:
          ENV_FILE: .env.test
        run: |
          poetry run pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: SignIn DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:latest